name: Update Threat Intel Feeds

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run threat intel collector
      run: |
        cd ArgonisIntel
        python argonisintel_v2.py
        
    - name: Commit and push if changes exist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ArgonisIntel/argonisintel_*_Feed.txt || echo "No files to add"
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update threat intel feeds"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push
        fi
